services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastapi-app
    restart: unless-stopped
    ports:
      - "8080:8000"
    environment:
      MONGO_URI: ${MONGO_URI:-mongodb+srv://230999_db_user:ansQfD6b7LzjDOcU@cluster0.bxckvrk.mongodb.net/}
      DB_NAME: ${DB_NAME:-assignmentdb}

      JWT_SECRET: ${JWT_SECRET:-supersecretkey}
      JWT_ALG: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
      CORS_ORIGINS: "*"
      APP_NAME: "FastAPI Render Demo"

    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8000/health/db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
